spring:
  application:
    name: spring-boot-lesson-3
    issue:
      max-allowed-books: 2
  datasource:
    url: jdbc:h2:mem:test
    username: li
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop